spring:
  application:
    name: spring-git-scraper
    description: "An app that extracts user data from a Git GUI. "
    environment: "${server.host}"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
  host: "localhost"
  servlet:
    context-path: "/scraper"
api:
  version:
    one: "/api/v1"
retry:
  maxAttempts: 3
  maxDelay: 300
github:
  base:
    url: "https://api.github.com/users"